version: '3'
services:
  service1a:
    image: ewilde/http-echo:latest
    command: -text service1a

  service1b:
    image: ewilde/http-echo:latest
    command:  -text service1b -response-rate=0.1 -response-delay=1000

  service1c:
    image: ewilde/http-echo:latest
    command: -text service1c -response-rate=1 -response-code=503

  load-balancer:
    image: nginx:1.13-alpine
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - service1a
      - service1b
      - service1c
    ports:
      - 80:80

  traffic-simulator:
    image: loadimpact/k6:0.20.0
    volumes:
      - ./../shared/traffic-simulator/script.js:/script.js
    command: ["run", "--vus", "10", "--duration", "300s" , "/script.js"]
    links:
      - load-balancer
      - influxdb
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/kubecon

  influxdb:
      build: ./../shared/influxdb/
      ports:
        - "8086:8086"

  grafana:
    build: ./../shared/graphana/
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
