version: '2'
services:
  traffic-simulator:
    build: ../shared/traffic-simulator
    volumes:
      - ./../shared/traffic-simulator/script.js:/script.js
    command: ["-wait", "http://load-balancer:80", "-timeout", "20s", "/root/k6", "run", "--vus", "10", "--duration", "300s" , "/script.js"]
    depends_on:
      - load-balancer
      - influxdb
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/kubecon

  load-balancer:
      image: nginx:1.13-alpine
      volumes:
        - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
      links:
        - service1a
        - service1b
        - service1c
        - service1d
      ports:
        - 80:80

  linkerd:
    image: buoyantio/linkerd:1.3.6
    depends_on:
      - consul-registrator
      - zipkin
    volumes:
      - ./linkerd/linkerd.config.yml:/config.yml
    command: /config.yml
    ports:
      - 4140:4140
      - 9990:9990

  consul:
    image: consul:1.0.6
    ports:
      - 8500:8500

  consul-registrator:
    image: gliderlabs/registrator:v7
    command: ["-internal", "consul://consul:8500"]
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  service1a:
    image: ewilde/http-echo:tracing
    command: zipkin:9410 -- /app/http-echo -text service1a
    environment:
      - SERVICE_NAME=service1
      - ZIPKIN_HOST=zipkin
    depends_on:
      - linkerd
  service1b:
    image: ewilde/http-echo:tracing
    command: zipkin:9410 -- /app/http-echo -text service1b -response-rate=2 -response-delay=1000
    environment:
      - SERVICE_NAME=service1
      - ZIPKIN_HOST=zipkin
    depends_on:
      - linkerd
  service1c:
    image: ewilde/http-echo:tracing
    command: zipkin:9410 -- /app/http-echo -text service1c -response-rate=40 -response-code=503
    environment:
      - SERVICE_NAME=service1
      - ZIPKIN_HOST=zipkin
    depends_on:
      - linkerd
  service1d:
    image: ewilde/http-echo:tracing
    command: zipkin:9410 -- /app/http-echo -text service1d
    environment:
      - SERVICE_NAME=service1
      - ZIPKIN_HOST=zipkin
    depends_on:
      - linkerd

  influxdb:
    build: ./../shared/influxdb/
    ports:
      - 8086:8086

  grafana:
    build: ./../shared/graphana/
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000

  zipkin:
    image: openzipkin/zipkin:2.6.1
    ports:
      - 9411:9411
      - 9410:9410
    environment:
      - SCRIBE_ENABLED=true
